name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test with Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: Wait for Services to Start
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          sleep 20  # waiting for PostgreSQL running
          docker compose exec db pg_isready -U user

      - name: Check Running Containers
        run: docker ps -a

      - name: Check Django Logs
        run: docker logs django-todo-app

      - name: Run Django Migrations
        run: docker compose exec backend python manage.py migrate

      - name: Run Django Tests
        run: docker compose exec backend python manage.py test

      - name: Tear Down Docker Containers
        run: docker compose down

  # push-to-docker-hub:
  #   name: Build & Push Docker Images
  #   runs-on: ubuntu-latest
  #   needs: build-and-test

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Log in to Docker Hub
  #       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  #     - name: Build & Tag Backend Image
  #       run: |
  #         docker build -t ${{ secrets.DOCKER_USERNAME }}/django-react-backend:latest ./backend
  #         docker tag ${{ secrets.DOCKER_USERNAME }}/django-react-backend:latest ${{ secrets.DOCKER_USERNAME }}/django-react-backend:${{ github.sha }}

  #     - name: Push Backend Image to Docker Hub
  #       run: |
  #         docker push ${{ secrets.DOCKER_USERNAME }}/django-react-backend:latest
  #         docker push ${{ secrets.DOCKER_USERNAME }}/django-react-backend:${{ github.sha }}

  #     - name: Build & Tag Frontend Image
  #       run: |
  #         docker build -t ${{ secrets.DOCKER_USERNAME }}/django-react-frontend:latest ./frontend
  #         docker tag ${{ secrets.DOCKER_USERNAME }}/django-react-frontend:latest ${{ secrets.DOCKER_USERNAME }}/django-react-frontend:${{ github.sha }}

  #     - name: Push Frontend Image to Docker Hub
  #       run: |
  #         docker push ${{ secrets.DOCKER_USERNAME }}/django-react-frontend:latest
  #         docker push ${{ secrets.DOCKER_USERNAME }}/django-react-frontend:${{ github.sha }}