name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test with Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: Wait for Services to Start
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          sleep 20  # ✅ PostgreSQL이 완전히 실행될 때까지 기다림
          docker compose exec db pg_isready -U user

      - name: Check Running Containers
        run: docker ps -a

      - name:
        run: docker logs django-todo-app

      - name: Run Django Migrations
        run: docker compose exec backend python manage.py migrate

      - name: Run Django Tests
        run: docker compose exec backend python manage.py test

    #   - name: Run Frontend Build
    #     run: docker compose exec frontend npm run build

      - name: Tear Down Docker Containers
        run: docker compose down